services:
  redis:
    container_name: opentracing-redis-server
    hostname: redis
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./bin:/usr/src/app/bin
      - ./src:/usr/src/app/src
      - ./include:/usr/src/app/include
    ports:
      - "6379:6379"
      - "1234:1234"
    environment:
      - REDIS_MODULE_PATH=/usr/local/lib/redis/modules/redisopentracing.so
    networks:
      - redis-opentracing-network

  redis-commander:
    container_name: opentracing-redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - redis-opentracing-network

networks:
  redis-opentracing-network:
    driver: bridge