REMOTE_REDIS_CONNECTION = False
TS_PREFIX = "OPENTRACING"

TRACE_EXECUTE_CMD = "TRACE.EXECUTE"
CMD_DELIM = "CMD"

CLIENT_ID_LABEL_KEY = "client_id"
COMMAND_TYPE_LABEL_KEY = "command_type"
INDEX_NAME_LABEL_KEY = "index_name"
COMMAND_LABEL_KEY = "command"
RETENTION_LABEL_KEY = "RETENTION"
